### ISSUE TITLE
Can't change account in xPub - bug in token exchange

### ISSUE THREAD

**Issue by chris-huggins** [elifesciences/elife-xpub#1904] opened 2019-04-09 08:50 UTC
We've had negative feedback that users can't change account. In xPub logging out, then pressing "log in" again simply logs the user in again as the same account, therefore they cannot change account.

On journal, logging out then pressing login again will direct the user to the ORCID login page. We should have the same experience on xPub login pages.

**Might be related to the issue we have with "login" linking to "continue" page instead of dashboard still. I can't find a ticket for this bug anymore though - @hdrury1**

**Comment by Cooryd** [comment] 2019-04-10 08:44
## Cause
This issue is caused by the difference in the xpub logout vs journal logout. xpub stores its own signed jwt in local storage on sign in and then removes it here :

https://github.com/elifesciences/elife-xpub/blob/48f40da3887f7c2129bac0f93f1795976f0e5295/packages/component-login/client/pages/LogoutPage.js#L8

when signing out. This is how the xpub app knows to redirect you to back to the login page if you try to hit any routes wrapped in `<AuthenticatedComponent>`

https://github.com/elifesciences/elife-xpub/blob/48f40da3887f7c2129bac0f93f1795976f0e5295/packages/component-elife-app/client/components/AuthenticatedComponent.js#L11

The login link button on the xpub sign in page directs you to http://elifesciences.org/submit (the same location as the blue button on the journal site). This is controlled by the journal site and will either redirect you to orcid login if the __journal__ session has no xpub jwt stored or redirect you to xpub with the jwt if it does (see: https://github.com/elifesciences/journal/blob/develop/src/Controller/SubmitController.php)

## Solution
We need to call a service on the journal or profile service to invalidate the journals stored jwt or clear the session similar to how they do on logging out https://github.com/elifesciences/journal/blob/7e38a99a9c52fd3fa2ecdeab1cda9bca0bc3a938/app/config/security.yml#L14

**Comment by hdrury1** [comment] 2019-04-11 11:21
Linked to #1652 potentially?

**Comment by chris-huggins** [comment] 2019-04-11 11:34
> Linked to #1652 potentially?

That's the one. I knew it was somewhere but couldn't find it, sorry. Looks like it's in To-do which is good as I think it would be ideal to fix soon?

**Comment by hdrury1** [comment] 2019-05-31 08:55
This looks to have been closed in #2020.

**Closed as completed by hdrury1** 2019-05-31 08:55 UTC
Labels: Bug
