### ISSUE TITLE
Review Deployments do not work

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#2036] opened 2019-05-28 13:12 UTC
See @Cooryd / @hdrury1

**Comment by giorgiosironi** [comment] 2019-05-28 14:25
[Previous investigation](https://elifesciences.slack.com/archives/C6LKMFK5Z/p1558095609145100):

<blockquote>
giorgio [2:39 PM]
in the review environments, the app containers are crashing on start - to be understood why

Erez Odier [2:41 PM]
ah that's why hannah couldn't see them i guess

giorgio [2:41 PM]

```
error: Database setup failed
error: ValidationError: username is not a property in User's schema
    at validationError (/home/xpub/node_modules/@pubsweet/base-model/src/index.js:11:3)
    at Object.keys.forEach.prop (/home/xpub/node_modules/@pubsweet/base-model/src/index.js:180:15)
    at Array.forEach (<anonymous>)
    at User.updateProperties (/home/xpub/node_modules/@pubsweet/base-model/src/index.js:176:29)
    at new BaseModel (/home/xpub/node_modules/@pubsweet/base-model/src/index.js:29:12)
    at new User (/home/xpub/packages/component-model-user/entities/user/index.js:5:1)
    at module.exports (/home/xpub/node_modules/pubsweet/node_modules/@pubsweet/db-manager/src/commands/add-user.js:10:16)
    at module.exports (/home/xpub/node_modules/pubsweet/node_modules/@pubsweet/db-manager/src/commands/setup-db.js:17:11)
    at <anonymous>
info: Stopping Application: elife-xpub--pr-1999-66f98bb7dd-dvjcj, PID: 15
```

the setupdb init container is the one having problems, it's running `npx pubsweet setupdb --username=pubsweet --password=pubsweet --email=fake@example.com --clobber`
the corresponding `postgres` pod seems alright

Erez Odier [2:44 PM]
We've had that problem for a while. but i we usually ignore it locally. Essentially, after the migrations run, pubsweet tries to add an admin user, but this fails because our user model doesn't have username as a property
i think

giorgio [2:52 PM]
happening on all pull requests at the moment:

```
$ kubectl get pod -lapp.kubernetes.io/component=app -lapp.kubernetes.io/part-of=elife-xpub
NAME                                   READY   STATUS                  RESTARTS   AGE
elife-xpub--pr-1979-659f99f5f8-vbkn9   0/2     Init:CrashLoopBackOff   2514       8d
elife-xpub--pr-1992-545f49c9c9-mndl5   0/2     Init:CrashLoopBackOff   44         3h
elife-xpub--pr-1992-698448d955-rqs7r   0/2     Init:CrashLoopBackOff   322        1d
elife-xpub--pr-1998-c7b5c9c7c-t2vgz    0/2     Init:CrashLoopBackOff   34         2h
elife-xpub--pr-1999-66f98bb7dd-dvjcj   0/2     Init:CrashLoopBackOff   19         1h
```

`0/2` because the init container fails, hence the 2 containers `elife-xpub` and `fakes3` are not started

</blockquote>

**Comment by giorgiosironi** [comment] 2019-05-28 15:42
https://github.com/elifesciences/elife-xpub/pull/2038 reproduces the issue perfectly but what does the database setup error mean? I'll try to dump the state of the database to see if it gives any insight.

**Comment by giorgiosironi** [comment] 2019-05-28 15:50
State seems consistent with the explanation: tables are created but a user cannot be added, and there is no `username` column which may be the cause.

```
I have no name!@elife-xpub--pr-2038-postgresql-0:/$ PGDATABASE=test PGUSER=postgres P
GPASSWORD=pw psql                                                                    
psql (10.5)
Type "help" for help.

test=# \l
                             List of databases
   Name    |  Owner   | Encoding | Collate | Ctype |   Access privileges   
-----------+----------+----------+---------+-------+-----------------------
 postgres  | postgres | UTF8     | C       | C     | 
 template0 | postgres | UTF8     | C       | C     | =c/postgres          +
           |          |          |         |       | postgres=CTc/postgres
 template1 | postgres | UTF8     | C       | C     | =c/postgres          +
           |          |          |         |       | postgres=CTc/postgres
 test      | postgres | UTF8     | C       | C     | 
(4 rows)

test=# \dt
                List of relations
 Schema |        Name         | Type  |  Owner   
--------+---------------------+-------+----------
 public | audit_log           | table | postgres
 public | ejp_name            | table | postgres
 public | entities            | table | postgres
 public | file                | table | postgres
 public | identity            | table | postgres
 public | journal             | table | postgres
 public | manuscript          | table | postgres
 public | migrations          | table | postgres
 public | organization        | table | postgres
 public | review              | table | postgres
 public | semantic_extraction | table | postgres
 public | team                | table | postgres
 public | user                | table | postgres
(13 rows)

test=# \d user
                                  Table "public.user"
      Column      |           Type           | Collation | Nullable |      Default      
------------------+--------------------------+-----------+----------+-------------------
 id               | uuid                     |           | not null | 
 created          | timestamp with time zone |           | not null | CURRENT_TIMESTAMP
 updated          | timestamp with time zone |           |          | 
 default_identity | text                     |           |          | 
Indexes:
    "user_pkey" PRIMARY KEY, btree (id)
Referenced by:
    TABLE "audit_log" CONSTRAINT "audit_log_user_id_fkey" FOREIGN KEY (user_id) REFERENCES "user"(id)
    TABLE "identity" CONSTRAINT "identity_user_id_fkey" FOREIGN KEY (user_id) REFERENCES "user"(id)
    TABLE "review" CONSTRAINT "review_user_id_fkey" FOREIGN KEY (user_id) REFERENCES "user"(id)
```

But what's the solution?

- add a `username` column
- customize the migration so that it doesn't add an admin user (do we need it?)
- customize the migration so that it adds the user with the right set of properties
- anything else?

**Comment by giorgiosironi** [comment] 2019-05-29 15:43
Assigned to me but I can't really do much in practice, reassign?

**Closed as completed** 2019-05-29 16:09 UTC
Labels: Server-Side, Deployment
