### ISSUE TITLE
Update stepper label in wizard

### ISSUE THREAD

**Issue by chris-huggins** [elifesciences/elife-xpub#1666] opened 2019-03-12 14:41 UTC
Change the label of the "submission" step of the wizard to "details". "Submission" is misleading as it's the term we use for the overall article, metadata etc.

![image](https://user-images.githubusercontent.com/41907215/54208983-d93e3900-44d4-11e9-87d2-76e64edcd1d0.png)

**Comment by hdrury1** [comment] 2019-03-12 15:19
This may be worth considering when we're looking at restructuring the codebase @diversemix.

**Comment by diversemix** [comment] 2019-03-13 08:33
Yeah - thanks for highlighting... @Cooryd / @damnhipster  ... would probably be worth renaming the components and files? no?

**Comment by hem-brahmbhatt** [comment] 2019-03-13 10:05
Yes, it's worth renaming parts of the code. We'll want to identify what the word submission is used for within the codebase. 

May be worth adding a dictionary of terms to the docs at some point.

**Comment by Cooryd** [comment] 2019-04-09 14:43
Duplicate of #1877

**Closed as completed by Cooryd** 2019-04-09 14:43 UTC
Labels: Client-Side
