### ISSUE TITLE
"Pre-fill my details using ORCID" not filling email or institution

### ISSUE THREAD

**Issue by chugginselifesciences** [elifesciences/elife-xpub#1031] opened 2018-11-13 16:56 UTC
**Describe the bug**
"pre-fill my details" with ORCID data isn't fully working. Only appears to bring in first and last name (not email or institution).

I've run into this problem before using elife-alfred-user@mailinator.com and now Susanna from the editorial team has raised it too.

Giuliano mentioned problems with account settings possibly blocking it, even though it should be a trusted user. However I'm sure this was working previously.
![image](https://user-images.githubusercontent.com/41907215/48429324-ca34bd80-e764-11e8-9c68-a9d7895d55c1.png)

**Steps To Reproduce**
Create a new submission then press "pre-fill my details".
 
**Expected behavior**
first name, last name, email address and institution would be auto-filled

**Screenshots**

**Device, Operating System and Browser**
MacBook Pro, Mojave, Chrome 70.

**Comment by diversemix** [comment] 2018-11-13 18:19
Probably coming from Journal nor ORCID

**Comment by diversemix** [comment] 2018-11-14 10:48
This needs looking into - I'm more worried about the misleading "from ORCiD" when it comes from Journal. 
Need to check the profile API as well as xPub

/cc @hdrury1

**Comment by jyenes** [comment] 2018-12-17 16:49
I was debugging and I found out that the issue can be coming from profiles API, hitting this url 
`https://prod--gateway.elifesciences.org/profiles/ewwboc7m` 
we get 
```JSON
{
"id": "ewwboc7m",
"name": {
"preferred": "Tamlyn Rhodes",
"index": "Rhodes, Tamlyn"
},
"orcid": "0000-0002-6277-0372",
"emailAddresses": [ ],
"affiliations": [ ]
}
```

I also created my own user on ORCID, but I was unable to find my profile on the profiles API, my ORCID id is `0000-0003-1077-7932`

**Comment by giorgiosironi** [comment] 2018-12-17 16:54
Possibilities:

- the user has non-public fields (on ORCID you can select to make it private to only yourself, private to trusted applications, or public). At least the university seems to be there, email address is unclear.
- the webhook that updates this profile (ORCID delivering it to profiles) is not working or being refused

**Comment by giorgiosironi** [comment] 2018-12-17 17:10
I think me and @GiancarloFusiello can take a look at the `profiles` side tomorrow.

**Comment by jyenes** [comment] 2018-12-17 17:14
I checked and my profile in ORCID is public, so should be the second option 

![screenshot 2018-12-17 at 17 10 11](https://user-images.githubusercontent.com/5822727/50103210-0acd9e00-021f-11e9-8b8a-743859f33513.png)

**Comment by GiancarloFusiello** [comment] 2018-12-18 14:00
I have created a new ORCID account and can confirm that the ORCID api is not sending emails or affiliations:
```
{
  'history': {
    'verified-primary-email': True,
    'last-modified-date': {
      'value': 1545138287393
    },
    'creation-method': 'MEMBER_REFERRED',
    'deactivation-date': None,
    'verified-email': True,
    'completion-date': None,
    'source': None,
    'claimed': True,
    'submission-date': {
      'value': 1545133363853
    }
  },
  'preferences': {
    'locale': 'EN'
  },
  'person': {
    'path': '/0000-0001-9214-6944/person',
    'researcher-urls': {
      'path': '/0000-0001-9214-6944/researcher-urls',
      'researcher-url': [],
      'last-modified-date': None
    },
    'last-modified-date': None,
    'name': {
      'visibility': 'PUBLIC',
      'credit-name': None,
      'last-modified-date': {
        'value': 1545133364081
      },
      'given-names': {
        'value': 'Giancarlo'
      },
      'path': '0000-0001-9214-6944',
      'created-date': {
        'value': 1545133363853
      },
      'source': None,
      'family-name': {
        'value': 'Fusiello'
      }
    },
    'other-names': {
      'path': '/0000-0001-9214-6944/other-names',
      'last-modified-date': None,
      'other-name': []
    },
    'external-identifiers': {
      'path': '/0000-0001-9214-6944/external-identifiers',
      'last-modified-date': None,
      'external-identifier': []
    },
    'emails': {
      'email': [],
      'last-modified-date': None,
      'path': '/0000-0001-9214-6944/email'
    },
    'biography': None,
    'addresses': {
      'path': '/0000-0001-9214-6944/address',
      'address': [],
      'last-modified-date': None
    },
    'keywords': {
      'path': '/0000-0001-9214-6944/keywords',
      'last-modified-date': None,
      'keyword': []
    }
  },
  'activities-summary': {
    'path': '/0000-0001-9214-6944/activities',
    'educations': {
      'path': '/0000-0001-9214-6944/educations',
      'last-modified-date': None,
      'education-summary': []
    },
    'peer-reviews': {
      'path': '/0000-0001-9214-6944/peer-reviews',
      'group': [],
      'last-modified-date': None
    },
    'fundings': {
      'path': '/0000-0001-9214-6944/fundings',
      'group': [],
      'last-modified-date': None
    },
    'last-modified-date': None,
    'works': {
      'path': '/0000-0001-9214-6944/works',
      'group': [],
      'last-modified-date': None
    },
    'employments': {
      'path': '/0000-0001-9214-6944/employments',
      'last-modified-date': None,
      'employment-summary': []
    }
  },
  'path': '/0000-0001-9214-6944',
  'orcid-identifier': {
    'uri': 'https://orcid.org/0000-0001-9214-6944',
    'host': 'orcid.org',
    'path': '0000-0001-9214-6944'
  }
}
```
Do we have a point of contact?

**Comment by giorgiosironi** [comment] 2018-12-18 14:15
What is your visibility settings for these? There should be 3 (public/trusted/private) available, to be checked first. Also I'm not sure if there are subresources to load or if everything should be in a single API call?
/cc @thewilkybarkid who worked on this

**Comment by GiancarloFusiello** [comment] 2018-12-18 14:33
Yes it seems each piece of information in your profile has it's own permissions. So even if you set your profile to Public, only the ORCID id and name are visible. I suspect most users do not realise that they have to set permissions for all fields.
```
{
  'activities-summary': {
    'peer-reviews': {
      'path': '/0000-0001-9214-6944/peer-reviews',
      'last-modified-date': None,
      'group': []
    },
    'fundings': {
      'path': '/0000-0001-9214-6944/fundings',
      'last-modified-date': None,
      'group': []
    },
    'employments': {
      'employment-summary': [
        {
          'path': '/0000-0001-9214-6944/employment/6988652',
          'created-date': {
            'value': 1545143053037
          },
          'visibility': 'PUBLIC',
          'source': {
            'source-client-id': None,
            'source-name': {
              'value': 'Giancarlo Fusiello'
            },
            'source-orcid': {
              'uri': 'https://orcid.org/0000-0001-9214-6944',
              'path': '0000-0001-9214-6944',
              'host': 'orcid.org'
            }
          },
          'department-name': None,
          'end-date': None,
          'put-code': 6988652,
          'role-title': 'Developer',
          'last-modified-date': {
            'value': 1545143053037
          },
          'start-date': {
            'month': {
              'value': '12'
            },
            'year': {
              'value': '2018'
            },
            'day': {
              'value': '03'
            }
          },
          'organization': {
            'disambiguated-organization': {
              'disambiguation-source': 'RINGGOLD',
              'disambiguated-organization-identifier': '385480'
            },
            'name': 'eLife Sciences Publications Ltd',
            'address': {
              'city': 'Cambridge',
              'country': 'GB',
              'region': 'Cambridgeshire'
            }
          }
        }
      ],
      'path': '/0000-0001-9214-6944/employments',
      'last-modified-date': {
        'value': 1545143053037
      }
    },
    'educations': {
      'path': '/0000-0001-9214-6944/educations',
      'last-modified-date': None,
      'education-summary': []
    },
    'path': '/0000-0001-9214-6944/activities',
    'last-modified-date': {
      'value': 1545143053037
    },
    'works': {
      'path': '/0000-0001-9214-6944/works',
      'last-modified-date': None,
      'group': []
    }
  },
  'orcid-identifier': {
    'uri': 'https://orcid.org/0000-0001-9214-6944',
    'path': '0000-0001-9214-6944',
    'host': 'orcid.org'
  },
  'preferences': {
    'locale': 'EN'
  },
  'path': '/0000-0001-9214-6944',
  'history': {
    'deactivation-date': None,
    'creation-method': 'MEMBER_REFERRED',
    'completion-date': None,
    'submission-date': {
      'value': 1545133363853
    },
    'verified-email': True,
    'verified-primary-email': True,
    'claimed': True,
    'source': None,
    'last-modified-date': {
      'value': 1545143053044
    }
  },
  'person': {
    'path': '/0000-0001-9214-6944/person',
    'researcher-urls': {
      'researcher-url': [],
      'last-modified-date': None,
      'path': '/0000-0001-9214-6944/researcher-urls'
    },
    'external-identifiers': {
      'path': '/0000-0001-9214-6944/external-identifiers',
      'last-modified-date': None,
      'external-identifier': []
    },
    'biography': None,
    'keywords': {
      'path': '/0000-0001-9214-6944/keywords',
      'keyword': [],
      'last-modified-date': None
    },
    'addresses': {
      'path': '/0000-0001-9214-6944/address',
      'last-modified-date': None,
      'address': []
    },
    'emails': {
      'email': [
        {
          'primary': False,
          'created-date': {
            'value': 1545133364081
          },
          'visibility': 'PUBLIC',
          'source': {
            'source-client-id': None,
            'source-name': {
              'value': 'Giancarlo Fusiello'
            },
            'source-orcid': {
              'uri': 'https://orcid.org/0000-0001-9214-6944',
              'path': '0000-0001-9214-6944',
              'host': 'orcid.org'
            }
          },
          'email': 'otheremail@example.com',
          'put-code': None,
          'path': None,
          'last-modified-date': {
            'value': 1545142987873
          },
          'verified': False
        },
        {
          'primary': True,
          'created-date': {
            'value': 1545133364081
          },
          'visibility': 'PUBLIC',
          'source': {
            'source-client-id': None,
            'source-name': {
              'value': 'Giancarlo Fusiello'
            },
            'source-orcid': {
              'uri': 'https://orcid.org/0000-0001-9214-6944',
              'path': '0000-0001-9214-6944',
              'host': 'orcid.org'
            }
          },
          'email': 'g.fusiello@elifesciences.org',
          'put-code': None,
          'path': None,
          'last-modified-date': {
            'value': 1545142985054
          },
          'verified': True
        }
      ],
      'last-modified-date': {
        'value': 1545142987873
      },
      'path': '/0000-0001-9214-6944/email'
    },
    'last-modified-date': {
      'value': 1545142987873
    },
    'name': {
      'created-date': {
        'value': 1545133363853
      },
      'visibility': 'PUBLIC',
      'source': None,
      'path': '0000-0001-9214-6944',
      'given-names': {
        'value': 'Giancarlo'
      },
      'last-modified-date': {
        'value': 1545133364081
      },
      'family-name': {
        'value': 'Fusiello'
      },
      'credit-name': None
    },
    'other-names': {
      'path': '/0000-0001-9214-6944/other-names',
      'last-modified-date': None,
      'other-name': []
    }
  }
}
```

**Comment by GiancarloFusiello** [comment] 2018-12-18 14:37
I can also confirm that the profiles database has been updated since changing my permissions:
```
{
  "id": "hq73wqe6",
  "name": {
    "preferred": "Giancarlo Fusiello",
    "index": "Fusiello, Giancarlo"
  },
  "orcid": "0000-0001-9214-6944",
  "emailAddresses": [
    {
      "access": "public",
      "value": "g.fusiello@elifesciences.org"
    }
  ],
  "affiliations": [
    {
      "access": "public",
      "value": {
        "name": [
          null,
          "eLife Sciences Publications Ltd"
        ],
        "address": {
          "formatted": [
            "Cambridge",
            "Cambridgeshire",
            "United Kingdom of Great Britain and Northern Ireland"
          ],
          "components": {
            "locality": [
              "Cambridge"
            ],
            "area": [
              "Cambridgeshire"
            ],
            "country": "United Kingdom of Great Britain and Northern Ireland"
          }
        }
      }
    }
  ]
}
```

**Comment by giorgiosironi** [comment] 2018-12-18 14:49
So we can't reproduce on a new user. There are other two cases to check from https://github.com/elifesciences/elife-xpub/issues/1031#issuecomment-447915022
- Tamlyn existing profile
- @jyenes own profile

**Comment by GiancarloFusiello** [comment] 2018-12-18 16:15
After further investigation, I'm quite confident that the Profiles service is working as expected. Next steps:

- Add more logging that should make it easier/quicker to identify issues
- Verify that xpub is making authenticated requests to `https://prod--gateway.elifesciences.org/profiles/<id>` (otherwise only public information is returned)
- Verify that Tamlyn has set permissions on email addresses and other data

**Comment by diversemix** [comment] 2018-12-18 18:04
@jyenes ... I suggest we create a test user we can all have to test. Maybe 'Albert Einstein' ... I think we should deprecate Tam :)

**Comment by jyenes** [comment] 2018-12-19 10:09
I was checking `https://prod--gateway.elifesciences.org/profiles` but I still can't find my profile there, neither the Giancarlo one, I have noticed the total on the top has changed now is higher number

**Comment by GiancarloFusiello** [comment] 2018-12-19 10:16
@jyenes how are you making the request? Can you paste the command you're using in full please?

**Comment by jyenes** [comment] 2018-12-19 10:33
I'm just entering the url on the browser `https://prod--gateway.elifesciences.org/profiles`

I have also created a dummy user for test 
credentials:
email: `albert@elife.com`
pass: `eLife12345!`
https://sandbox.orcid.org/0000-0003-2895-4626

and this one it also not appearing on the list

**Comment by GiancarloFusiello** [comment] 2018-12-19 10:53
`/profiles` appears to be paginated by default. The default response is to show page 1 and limited to 20 results per page. Also, if you do not send an authentication token you will only receive public profiles. If you are looking for your profile, make sure it is set to be publicly visible and try incrementing the page query param. e.g `https://prod--gateway.elifesciences.org/profiles?page=1`.

**Comment by jyenes** [comment] 2018-12-19 11:13
is there anyway to add query?
like ` https://prod--gateway.elifesciences.org/profiles?orcid="0000-0003-2895-4626"`???

**Comment by diversemix** [comment] 2018-12-20 14:35
Further investigation with @jyenes + @GiancarloFusiello ...
- We confirmed a `Public` email is always accessible on the Profile's API, however we could not test the `Trusted` or `Private` one as we could not confirm the authentication was working as exected, see...
- Using `curl` ( `curl -vk -H "Authentication: ${ELIFE_API_GATEWAY_SECRET}" http://prod--gateway.elife.internal/profiles/j9tn67y4 | jq` ) did not get us the email - even though it was set to `Trusted`

@GiancarloFusiello is going to confirm this is working before any further xpub work.

**Comment by thewilkybarkid** [comment] 2018-12-20 14:39
Ah, this will be https://github.com/elifesciences/issues/issues/4318.

**Comment by GiancarloFusiello** [comment] 2018-12-21 14:52
https://github.com/elifesciences/issues/issues/4318 has now been merged and I can confirm that it is working as expected. In order to test, from within the elife VPC network, you can use the following command: `curl -s -H 'x-consumer-groups: view-restricted-profiles' http://prod--gateway.elife.internal/profiles/<id>` or externally use `curl -s -H 'Authorization: ${ELIFE_API_GATEWAY_SECRET}' -H 'x-consumer-groups: view-restricted-profiles' https://prod--gateway.elifesciences.org/profiles/<id>`

**Comment by diversemix** [comment] 2019-01-07 10:33
I'm happy this is working now, there is still one small bug on the profile service (see https://github.com/elifesciences/issues/issues/3365). I will close this now, as this is not strictly dependant on the user tool going in ( see #1247 ) - but this tool has helped me pin point this issue.

**Closed by diversemix** 2019-01-07 10:33 UTC
Labels: Bug, Client-Side
