### ISSUE TITLE
Scroll to first validation error when user clicks 'Next'

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#516] opened 2018-08-22 08:58 UTC
**User Story:**

_As a submitter I want a clear indication of where input is still needed before I can proceed to the next step of the wizard._

**Product requirements/Acceptance criteria:**

Functional:

- When the user clicks 'Next' the focus should move to the first invalid field and the screen scroll accordingly.

**Comment by diversemix** [comment] 2018-11-13 18:18
Duplicate of #330

**Closed** 2018-11-13 18:18 UTC
Labels: Client-Side, Submission Wizard
