### ISSUE TITLE
Cannot add or remove more supporting files

### ISSUE THREAD

**Issue by hem-brahmbhatt** [elifesciences/elife-xpub#1750] opened 2019-03-22 16:00 UTC
**Steps to reproduce:**

- Go to https://staging--xpub.elifesciences.org
- Login
- New Submission
- Upload a supporting file

_Should be able to add or remove all supporting files_
**Instead, cannot do either**

<img width="938" alt="Screen Shot 2019-03-22 at 15 59 01" src="https://user-images.githubusercontent.com/2573277/54836247-c0473c00-4cbb-11e9-8dd3-24bc0310801c.png">

**Comment by diversemix** [comment] 2019-03-22 16:13
Unable to reproduce ... still trying...

**Comment by diversemix** [comment] 2019-03-22 16:29
@damnhipster ... unless you want to keep this open "just in case" .. I suggest we close this.

**Closed as completed** 2019-03-22 16:29 UTC
Labels: Bug
