### ISSUE TITLE
Investigate React error

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#2212] opened 2019-07-02 16:48 UTC
A user encountered the following error when accessing the Details step of the wizard. The error threw on two separate submissions:

`Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.`

Windows10, Chrome Version 75.0.3770.100

The user was able to complete a submission in Firefox subsequently

![error_elife](https://user-images.githubusercontent.com/17023702/60530809-84c40100-9cf1-11e9-9b34-87f6ff2d34a7.jpg)

**Comment by erezmus** [comment] 2019-07-04 14:32
I tried to reproduce the issue on production with the same data on browserstack with same os and browser version but couldn't see it happening.

Do we have error reporting on new relic?

/cc @diversemix

**Comment by diversemix** [comment] 2019-07-05 07:45
This has happened again in production... Chrome 75.0.3770 and Windows 10 for this user too

**Comment by hdrury1** [comment] 2019-07-05 07:50
I've watched both recordings and seen the user encounter the error by clicking 'Next' on the files step.

**Comment by erezmus** [comment] 2019-07-05 10:27
Recording with error

https://insights.hotjar.com/r?site=443270&recording=2321089964

**Comment by Cooryd** [comment] 2019-07-05 13:30
On checking hotjar recordings it looks like this user refreshed then was able to proceed to submitting this submission. We weren't able to find anything in loggly or new relic to better identify what caused the error. Will close this and try to get some more identifiable error handling as part of #2237

**Closed as completed by Cooryd** 2019-07-05 13:30 UTC
Labels: Bug, Client-Side, Investigation
