### ISSUE TITLE
Upload Manuscript Fails

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#538] opened 2018-08-30 15:31 UTC
Uploading a 5Meg manuscript is causing issues:

- go to the `Files` page of the wizard.
- upload a ~5M Manuscript
- When its done check the WS Frames (see screen shot) 
- WS frames sometimes have "Opcode -1"

If you find this doesn't click Back then Next and repeat the upload.
![image](https://user-images.githubusercontent.com/8524685/44994238-9a637f80-af95-11e8-9465-fb01cbf072b6.png)

**Comment by dryhten** [comment] 2018-09-04 11:28
I tried exactly what you described (both with and without valid auth token) and I never get opcode -1. What file did you use? I generated a random pdf of 5MB.

**Comment by diversemix** [comment] 2018-09-04 14:15
[elife-35786-v2.pdf](https://github.com/elifesciences/elife-xpub/files/2348977/elife-35786-v2.pdf)
I've attached the file I used.

**Comment by dryhten** [comment] 2018-09-04 15:07
I tried with that file on both Chromium and Firefox and I still don't get `Opcode -1`. Can you try it again here? https://demo--xpub.elifesciences.org/

**Comment by diversemix** [comment] 2018-09-04 16:01
Ok, just tried it again... I don't get the `Opcode -1` error ... just the `Bad auth token` and the fact the upload fails to complete.

**Comment by dryhten** [comment] 2018-09-12 12:58
Is this issue still valid? Now everything seems to work fine on the demo website.

**Comment by hdrury1** [comment] 2018-09-14 10:45
I'm going to close this down as I've also been unable to reproduce the error. Obviously @diversemix please do let us know if the problem persists for you!

**Closed** 2018-09-14 10:45 UTC
Labels: Bug, Client-Side, Server-Side

**Comment by diversemix** [comment] 2018-09-17 09:42
I can confirm it now works fine on the demo site :)
