### ISSUE TITLE
Premature Validation

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#842] opened 2018-10-19 13:36 UTC
Validation on all the pages is happening on auto save (I think) not when next is clicked.

This results in red validation warnings on fields that you have not yet come across.

**Comment by tamlyn** [comment] 2018-10-22 15:51
The whole form validates whenever any field is blurred. This is normal and usually isn't visible to users because validation messages aren't shown unless a field is also marked as touched. 

There's a bug with the file upload control where it gets marked as touched while it's uploading but before it has a value set from the upload. This results in a red border around the control even though there is no error. 

I haven't seen premature validation validation warnings affecting any other fields but if anyone else has, please add reproduction steps here.

**Comment by hdrury1** [comment] 2018-10-23 07:32
1. Click into cover letter editor.
2. See validation error for cover letter and file upload.

**Comment by diversemix** [comment] 2018-10-23 07:33
Currently on staging (commit `cf26178`) ... I see it on the following page "Submission" with "Subject Areas" - after changing the "manuscript title" then focusing on the "Article type" field I can see an issue with "Subject areas"

**Comment by diversemix** [comment] 2018-10-23 07:34
On the following "Editors" page I see validation errors on "Suggest Reviewing Editors" having only selected 2 "Suggest Senior Editors"

**Comment by diversemix** [comment] 2018-10-23 07:36
... and also the "I declare that, to the best of my knowledge, these experts have no conflict of interest" field shows a validation error.

**Comment by diversemix** [comment] 2018-10-23 07:38
The final "Disclosure" page also shows a validation error on "I agree on behalf of all authors"  after filling out the "Acknowleged by" and then clicking off the field.

**Comment by tamlyn** [comment] 2018-10-23 08:04
Ok! Ok! Enough! Stop! 😆

**Comment by tamlyn** [comment] 2018-10-24 11:15
As discovered yesterday, this issue only occurs when `NODE_ENV=production`.

**Closed** 2018-10-24 12:49 UTC
Labels: Bug, Client-Side
