### ISSUE TITLE
Show an error state when supporting file uploads are cancelled (by page reload)

### ISSUE THREAD

**Issue by chris-huggins** [elifesciences/elife-xpub#1378] opened 2019-01-22 17:35 UTC
## Problem / Motivation

- WHO author completing an initial submission
- WHEN and WHERE when uploading one or more supporting files and reloading the page
- WHAT files cancelled by the reload should be shown in an error state
- WHY do they want this? So that they are aware the files will not make it to eJP

## Proposed solution

Show an error state

## Clarification needed and assumptions

- Are we definitely unable to improve this for MVP by allowing the errors to be removed without restarting file upload?

## User interface / Wireframes

**Cancelled files are shown in a generic error state**

![image](https://user-images.githubusercontent.com/41907215/51553853-cf507000-1e6b-11e9-92fc-4b493cb401d1.png)

**below 768px**

![image](https://user-images.githubusercontent.com/41907215/51553935-f8710080-1e6b-11e9-9ec8-4e7903ca5d36.png)

**Comment by hdrury1** [comment] 2019-01-23 10:20
Note that for MVP we will not be introducing the trash icon. A user will remove all items and start again.

I've raised a ticket for improving the feature (adding the trash icon and functionality) here: #1382

**Comment by diversemix** [comment] 2019-01-25 13:31
@hdrury1 is this a duplicate of #1362 ?

**Comment by hdrury1** [comment] 2019-01-25 13:32
@diversemix I thought it was but after discussion the other day didn't we determine this ticket encompassed the front end work and the other the server side?

**Comment by diversemix** [comment] 2019-01-25 13:33
Ah ok ... so the server now needs to not delete the file entity when it fails? (Otherwise they won't show up) is that correct @hdrury1 ?

**Comment by hdrury1** [comment] 2019-01-25 13:34
I guess fulfilling this ticket will also solve the bug :)

**Closed as completed** 2019-07-10 11:57 UTC
Labels: Client-Side
