### ISSUE TITLE
Production AWS Creds deny s3

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#791] opened 2018-10-15 09:31 UTC
```
elife@prod--xpub:~$ aws s3 cp test-file s3://prod-elife-xpub/test-file
upload failed: ./test-file to s3://prod-elife-xpub/test-file An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
```

**Comment by damnhipster** [comment] 2018-10-18 15:09
Duplicate of #826

**Closed** 2018-10-19 13:04 UTC
Labels: Bug, Deployment
