### ISSUE TITLE
validation error when no supporting files added prevents user continuing

### ISSUE THREAD

**Issue by chris-huggins** [elifesciences/elife-xpub#1912] opened 2019-04-11 08:36 UTC
![image](https://user-images.githubusercontent.com/41907215/55942840-34cb2600-5c3d-11e9-85a3-87538c7bcea9.png)

We had angry feedback on hotjar with the above screenshot

**Comment by chris-huggins** [comment] 2019-05-03 08:40
@hdrury1 I've not experienced this bug recently so wonder if we can close it or need to investigate to see if it's still occurring at all first?

**Comment by hdrury1** [comment] 2019-05-14 12:31
I'm also not able to reproduce, FYI. @erezmus feel free to close this if you aren't either.

**Comment by erezmus** [comment] 2019-05-15 12:56
I've had a look code wise and this could happen if there is somehow a mismatch between the manuscript entry in the `files` property of the manuscript object and the `fileStatus` not being 'READY'.

Since we haven't observed this bug and haven't been able to reproduce. Closing for now.

**Closed as completed by erezmus** 2019-05-15 12:56 UTC
Labels: Bug
