### ISSUE TITLE
k8s pipeline needs more resource

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#281] opened 2018-07-02 14:03 UTC
**Describe the bug**
The k8s pipeline still regularly fails with 

```
ERROR: Job failed (system failure): timedout waiting for pod to start
```

**To Reproduce**
Not easy to.

**Comment by g-sam** [comment] 2018-07-02 15:30
This is lack of resources
A big issue for resources is branch deletions not being mirrored to Gitlab. We need to make sure we periodically go there and delete merged branches.

**Comment by diversemix** [comment] 2018-07-02 18:42
Ok ... can we automate this somehow? Maybe with a cron job locally?

When you say "go there" ... do you mean here: https://gitlab.coko.foundation/xpub/xpub-elife

**Comment by diversemix** [comment] 2018-07-11 09:48
@g-sam ... Please go ahead - I've talked with @BlueReZZ and this its okay to increase the resources on the infrastructure.

**Comment by diversemix** [comment] 2018-07-11 09:50
As another note - we are going to move onto EKS (AWS) in the not-too-distant future - so we are not expecting this to be a long term thing.

**Comment by g-sam** [comment] 2018-07-11 09:54
👍 We can do this now. YLD will bill you for the amount we use up to $500.

**Comment by damnhipster** [comment] 2018-07-11 11:12
We think this is caused by the CPU usage of the Kubernetes nodes. We've increased the number of nodes from 6 up to 9 to help the situation, and we're monitoring to see if it helps.

We require burst performance during the day, but it seems that we're constantly running above the baseline CPU performance which affects the amount we can burst. Hopefully adding more nodes is enough, if not, we're also looking at whether the `t2.medium` instance is appropriate for our usage.

**Comment by damnhipster** [comment] 2018-07-11 13:37
We've managed to reduce the baseline performance of the cluster to a threshold where we don't run out of CPU credits for bursts during the day. This may help with #295

**Closed** 2018-07-11 13:37 UTC
Labels: Bug, Deployment
